apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: mlbdev
spec:
  image: us.gcr.io/container-suite/crunchy-postgres-ha:ubi8-13.2-ci-latest
  openshift: false
  port: 5432
  postgresVersion: 13
  instances:
    - name: 'pgc'
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "freenas-nfs-csi"
        resources:
          requests:
            storage: 10Gi
  archive:
    pgbackrest:
      image: us.gcr.io/container-suite/crunchy-pgbackrest:ubi8-13.2-ci-latest
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            storageClassName: "freenas-nfs-csi"
            resources:
              requests:
                storage: 10Gi
  proxy:
    pgBouncer:
      image: us.gcr.io/container-suite/crunchy-pgbouncer:ubi8-13.2-ci-latest
      port: 5432
      replicas: 1
