apiVersion: v1
kind: Endpoints
metadata:
  name: findev-lb
  namespace: finance
subsets:
- addresses:
  - "findev-ha"
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: findev-lb
  namespace: sports
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
